// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApplication.Models;

namespace TestApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestApplication.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action",
                            Description = "Action & Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Horror",
                            Description = "Horror , Suspense , Fear"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Science Fiction",
                            Description = "Futuristic and Technologic"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Fantasy",
                            Description = "Magic and Wonder"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Romance",
                            Description = "Love Story"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Comedy",
                            Description = "Laugh feel good humor"
                        });
                });

            modelBuilder.Entity("TestApplication.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            VideoId = 1,
                            CategoryId = 1,
                            Director = "Quenton Tarentino",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_UY1200_CR90,0,630,1200_AL_.jpg",
                            InStock = true,
                            LongDescription = "Jamie Fox Plays a freed slave turned Bounty-Hunter",
                            Price = 15m,
                            ShortDescription = "Freed Slave turned Bounty-Hunter",
                            Title = "Django Unchained"
                        },
                        new
                        {
                            VideoId = 2,
                            CategoryId = 1,
                            Director = "Zack Snyder",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/20/Batman_v_Superman_poster.jpg",
                            InStock = true,
                            LongDescription = "Batman and Superman face off conspired by Lex Luther",
                            Price = 15m,
                            ShortDescription = "Batman vs Superman",
                            Title = "Batman vs Superman"
                        },
                        new
                        {
                            VideoId = 3,
                            CategoryId = 1,
                            Director = "Jonas Akerlund",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMzA5MjNjODEtOWYxYi00OTdmLTlhNTAtN2VhMTMxNWJjM2ZmXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_UY1200_CR90,0,630,1200_AL_.jpg",
                            InStock = true,
                            LongDescription = "Retired Hitman Duncan is betrayed by his employer after 40 yrs of service to cheat him out of his retirment fund",
                            Price = 15m,
                            ShortDescription = "Retired Hitman Betrayed",
                            Title = "Polar"
                        },
                        new
                        {
                            VideoId = 4,
                            CategoryId = 1,
                            Director = "Andrew Davis",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/3d/StevenSeagalUnderSiege_cover.jpg",
                            InStock = true,
                            LongDescription = "Naval Chief Casey Ryback stops naval hijacking kicking ass and taking names",
                            Price = 15m,
                            ShortDescription = "Naval Chief Casey Ryback stops naval hijacking",
                            Title = "Under Siege"
                        },
                        new
                        {
                            VideoId = 5,
                            CategoryId = 1,
                            Director = "Mark L. Lester",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/d/d9/Commandoposter.jpg/220px-Commandoposter.jpg",
                            InStock = true,
                            LongDescription = "A retired Special Forces colonel tries to save his daughter",
                            Price = 15m,
                            ShortDescription = "Arnold Is not playing around",
                            Title = "Commando"
                        },
                        new
                        {
                            VideoId = 6,
                            CategoryId = 2,
                            Director = "Adrian Lyne",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/51BAJ8zc13L._SY445_.jpg",
                            InStock = true,
                            LongDescription = "Vietnam Vet Jacob Singer Falls into purgatory",
                            Price = 15m,
                            ShortDescription = "Vietnam Vet suffers hallucinations",
                            Title = "Jacobs Ladder"
                        },
                        new
                        {
                            VideoId = 7,
                            CategoryId = 2,
                            Director = "Zack Snyder",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/16/Dawn_of_the_Dead_2004_movie.jpg",
                            InStock = true,
                            LongDescription = "A nurse, policeman, a couple and others survive in a mall with zombies outside",
                            Price = 15m,
                            ShortDescription = "Trapped in a mall zombies outside",
                            Title = "Dawn of the Dead"
                        },
                        new
                        {
                            VideoId = 8,
                            CategoryId = 2,
                            Director = "Rob Reiner",
                            ImageUrl = "https://static.wikia.nocookie.net/stephenking/images/3/30/Miseryfilm.jpg/revision/latest/scale-to-width-down/340?cb=20150727205054",
                            InStock = true,
                            LongDescription = "Crazy Lady kidnaps her favorite Author and forces him to rewrite a book from a series",
                            Price = 15m,
                            ShortDescription = "Crazy fan kidnaps her favorite Author",
                            Title = "Misery"
                        },
                        new
                        {
                            VideoId = 9,
                            CategoryId = 2,
                            Director = "James Wan",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/41J9mRV5AUL.jpg",
                            InStock = true,
                            LongDescription = "Mastermind who likes puppets traps people in elaborite ways to teach them a lession",
                            Price = 15m,
                            ShortDescription = "Mastermind traps people in elaborite ways",
                            Title = "Saw"
                        },
                        new
                        {
                            VideoId = 10,
                            CategoryId = 2,
                            Director = "David Robert Mitchell",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMmU0MjBlYzYtZWY0MC00MjliLWI3ZmUtMzhlZDVjMWVmYWY4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY1200_CR90,0,630,1200_AL_.jpg",
                            InStock = true,
                            LongDescription = "A Ghost that hunts and kills the last person you sleep with.",
                            Price = 15m,
                            ShortDescription = "Sexually Transmitted Ghost",
                            Title = "It Follows"
                        },
                        new
                        {
                            VideoId = 11,
                            CategoryId = 3,
                            Director = "Ridley Scott",
                            ImageUrl = "https://thumbor.forbes.com/thumbor/237x300/http://b-i.forbesimg.com/daviddisalvo/files/2013/07/prometheus_main-237x300.jpg",
                            InStock = true,
                            LongDescription = "Human Explorers follow ancient clues to find their creators",
                            Price = 15m,
                            ShortDescription = "Human Explorers search for their creators",
                            Title = "Prometheus"
                        },
                        new
                        {
                            VideoId = 12,
                            CategoryId = 3,
                            Director = "Pete Travis",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Dredd2012Poster.jpg/220px-Dredd2012Poster.jpg",
                            InStock = true,
                            LongDescription = "Judges are the jugde, jury, and executioner of the apocolyptic future.",
                            Price = 15m,
                            ShortDescription = "The law of the wasteland",
                            Title = "Dredd"
                        },
                        new
                        {
                            VideoId = 13,
                            CategoryId = 3,
                            Director = "George Miller",
                            ImageUrl = "https://i.ytimg.com/vi/i2gVXd7FzhQ/maxresdefault.jpg",
                            InStock = true,
                            LongDescription = "Lord of the Wasteland Humongous, the iatola of rock and rolla",
                            Price = 15m,
                            ShortDescription = "JUST WALK AWAY",
                            Title = "Mad Max 2"
                        },
                        new
                        {
                            VideoId = 14,
                            CategoryId = 3,
                            Director = "John Carpenter",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNGViZWZmM2EtNGYzZi00ZDAyLTk3ODMtNzIyZTBjN2Y1NmM1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg",
                            InStock = true,
                            LongDescription = "Shape-shifting alien found in the artic that is dangerous.",
                            Price = 15m,
                            ShortDescription = "Alien shape-shifter in Antartica",
                            Title = "The Thing"
                        },
                        new
                        {
                            VideoId = 15,
                            CategoryId = 3,
                            Director = "Doug Liman",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/f/f9/Edge_of_Tomorrow_Poster.jpg",
                            InStock = true,
                            LongDescription = "I dont care if he is a scientologist",
                            Price = 15m,
                            ShortDescription = "Tom Cruise is amazing",
                            Title = "Edge of Tomorrow"
                        },
                        new
                        {
                            VideoId = 16,
                            CategoryId = 4,
                            Director = "Peter Jackson",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_UY1200_CR90,0,630,1200_AL_.jpg",
                            InStock = true,
                            LongDescription = "A Hobbit journeys with a ring with a band of Dwarfs",
                            Price = 15m,
                            ShortDescription = "A Hobbit journeys with a ring",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            VideoId = 17,
                            CategoryId = 4,
                            Director = "David Yates",
                            ImageUrl = "https://tuftsdaily.com/wp-content/uploads/2018/11/i1G4sQb.jpg",
                            InStock = true,
                            LongDescription = "I feel bad for Johnny Depth",
                            Price = 15m,
                            ShortDescription = "Wizard/Animal enthusiast also facism",
                            Title = "Fantastic Beasts, The Crimes Of Grindelwald"
                        },
                        new
                        {
                            VideoId = 18,
                            CategoryId = 4,
                            Director = "Chris Columbus",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UY1200_CR90,0,630,1200_AL_.jpg",
                            InStock = true,
                            LongDescription = "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family",
                            Price = 15m,
                            ShortDescription = "Daniel Radcliffe",
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            VideoId = 19,
                            CategoryId = 4,
                            Director = "Robert Zemeckis",
                            ImageUrl = "https://deadline.com/wp-content/uploads/2020/10/witches-1-e1601613994504.jpg",
                            InStock = true,
                            LongDescription = "A young boy and his grandmother have a run-in with a coven of witches and thier leader",
                            Price = 15m,
                            ShortDescription = "Witches in a hotel",
                            Title = "Witches"
                        },
                        new
                        {
                            VideoId = 20,
                            CategoryId = 4,
                            Director = "Stephen Gaghan",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMDNkODA5ZGQtODczOS00OTQxLThhMTItMjk0ZmNhMDM0YjNmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
                            InStock = true,
                            LongDescription = "A physician who can talk to animals",
                            Price = 15m,
                            ShortDescription = "Robert Downey Jr is Dr. Dolittle",
                            Title = "Dolittle"
                        },
                        new
                        {
                            VideoId = 21,
                            CategoryId = 5,
                            Director = "Michael Curtiz",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UY1200_CR83,0,630,1200_AL_.jpg",
                            InStock = true,
                            LongDescription = "Boring",
                            Price = 15m,
                            ShortDescription = "Rick Blaine owns a nightclub",
                            Title = "Casablanca"
                        },
                        new
                        {
                            VideoId = 22,
                            CategoryId = 5,
                            Director = "Sam Wood",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/aa/A_Night_at_the_Opera_film_poster.jpg",
                            InStock = true,
                            LongDescription = "A physician who can talk to animals",
                            Price = 15m,
                            ShortDescription = "Boring",
                            Title = "A Night at the Opera"
                        },
                        new
                        {
                            VideoId = 23,
                            CategoryId = 5,
                            Director = "Frank Capra",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/d/dc/It-happened-one-night-poster.jpg",
                            InStock = true,
                            LongDescription = "A physician who can talk to animals",
                            Price = 15m,
                            ShortDescription = "Boring",
                            Title = "It Happened One Night"
                        },
                        new
                        {
                            VideoId = 24,
                            CategoryId = 5,
                            Director = "Guillermo del Toro",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/81+H9++xgTL.jpg",
                            InStock = true,
                            LongDescription = "A physician who can talk to animals",
                            Price = 15m,
                            ShortDescription = "Boring",
                            Title = "The Shape Of Water"
                        },
                        new
                        {
                            VideoId = 25,
                            CategoryId = 5,
                            Director = "Stanley Donen",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Singin%27_in_the_Rain_%281952_poster%29.jpg/1200px-Singin%27_in_the_Rain_%281952_poster%29.jpg",
                            InStock = true,
                            LongDescription = "A physician who can talk to animals",
                            Price = 15m,
                            ShortDescription = "Boring",
                            Title = "Singin in the rain"
                        },
                        new
                        {
                            VideoId = 26,
                            CategoryId = 6,
                            Director = "Tamra Davis",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BZWMxZWE1ZjQtYzAyNS00NjEwLTgwM2ItMWI2NWVhZGJiYjk3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY1200_CR86,0,630,1200_AL_.jpg",
                            InStock = true,
                            LongDescription = "Friends are forced to sell weed to get friend out of jail.",
                            Price = 15m,
                            ShortDescription = "Friends sell weed",
                            Title = "Half Baked"
                        },
                        new
                        {
                            VideoId = 27,
                            CategoryId = 6,
                            Director = "Jesse Dylan",
                            ImageUrl = "https://resizing.flixster.com/5374dDGmXYamiLqRJ9DG1rjidOc=/206x305/v2/https://flxt.tmsimg.com/assets/p28741_p_v10_aa.jpg",
                            InStock = true,
                            LongDescription = "Red-man and Method Man go to Harvard.",
                            Price = 15m,
                            ShortDescription = "Red-man and Method man",
                            Title = "How High"
                        },
                        new
                        {
                            VideoId = 28,
                            CategoryId = 6,
                            Director = "Edgar Wright",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMzg4MDJhMDMtYmJiMS00ZDZmLThmZWUtYTMwZDM1YTc5MWE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
                            InStock = true,
                            LongDescription = "Cop gets transferred",
                            Price = 15m,
                            ShortDescription = "Buddy Cop film",
                            Title = "Hot Fuzz"
                        },
                        new
                        {
                            VideoId = 29,
                            CategoryId = 6,
                            Director = "Ben Stiller",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/d6/Tropic_thunder_ver3.jpg",
                            InStock = true,
                            LongDescription = "Hilarious",
                            Price = 15m,
                            ShortDescription = "Hilarious",
                            Title = "Tropic Thunder"
                        },
                        new
                        {
                            VideoId = 30,
                            CategoryId = 6,
                            Director = "Chris Farley",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/16/Beverly_Hills_Ninja_poster.jpg",
                            InStock = true,
                            LongDescription = "Fat Ninja",
                            Price = 15m,
                            ShortDescription = "Fat Ninja",
                            Title = "Beverly Hills Ninja"
                        });
                });

            modelBuilder.Entity("TestApplication.Models.Video", b =>
                {
                    b.HasOne("TestApplication.Models.Category", "Category")
                        .WithMany("Videos")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TestApplication.Models.Category", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
